# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bars_pb2 as bars__pb2


class BarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecentBars = channel.unary_unary(
                '/datasvc.v1.BarService/GetRecentBars',
                request_serializer=bars__pb2.GetRecentBarsRequest.SerializeToString,
                response_deserializer=bars__pb2.BarsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/datasvc.v1.BarService/HealthCheck',
                request_serializer=bars__pb2.HealthRequest.SerializeToString,
                response_deserializer=bars__pb2.HealthResponse.FromString,
                _registered_method=True)


class BarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRecentBars(self, request, context):
        """Return the most recent `count` closed bars for (symbol, timeframe),
        sorted ascending by ts. Bars are read straight from Postgres — no
        TradingView call is triggered.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Readiness check used by clients (bots) before starting trading loops.
        Returns ready=true when bar_count >= min_bars for (symbol, timeframe).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecentBars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecentBars,
                    request_deserializer=bars__pb2.GetRecentBarsRequest.FromString,
                    response_serializer=bars__pb2.BarsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=bars__pb2.HealthRequest.FromString,
                    response_serializer=bars__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datasvc.v1.BarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datasvc.v1.BarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecentBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datasvc.v1.BarService/GetRecentBars',
            bars__pb2.GetRecentBarsRequest.SerializeToString,
            bars__pb2.BarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/datasvc.v1.BarService/HealthCheck',
            bars__pb2.HealthRequest.SerializeToString,
            bars__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
