# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bars.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'bars.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbars.proto\x12\ndatasvc.v1\"}\n\x03\x42\x61r\x12\x0e\n\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x12\n\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n\x05\x63lose\x18\x05 \x01(\x01R\x05\x63lose\x12\x16\n\x06volume\x18\x06 \x01(\x01R\x06volume\"b\n\x14GetRecentBarsRequest\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x14\n\x05\x63ount\x18\x03 \x01(\x05R\x05\x63ount\"3\n\x0c\x42\x61rsResponse\x12#\n\x04\x62\x61rs\x18\x01 \x03(\x0b\x32\x0f.datasvc.v1.BarR\x04\x62\x61rs\"`\n\rHealthRequest\x12\x16\n\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1c\n\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x19\n\x08min_bars\x18\x03 \x01(\x05R\x07minBars\"m\n\x0eHealthResponse\x12\x14\n\x05ready\x18\x01 \x01(\x08R\x05ready\x12%\n\x0e\x62\x61rs_available\x18\x02 \x01(\x05R\rbarsAvailable\x12\x1e\n\x0blast_bar_ts\x18\x03 \x01(\x03R\tlastBarTs2\x9f\x01\n\nBarService\x12K\n\rGetRecentBars\x12 .datasvc.v1.GetRecentBarsRequest\x1a\x18.datasvc.v1.BarsResponse\x12\x44\n\x0bHealthCheck\x12\x19.datasvc.v1.HealthRequest\x1a\x1a.datasvc.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bars_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BAR']._serialized_start=26
  _globals['_BAR']._serialized_end=151
  _globals['_GETRECENTBARSREQUEST']._serialized_start=153
  _globals['_GETRECENTBARSREQUEST']._serialized_end=251
  _globals['_BARSRESPONSE']._serialized_start=253
  _globals['_BARSRESPONSE']._serialized_end=304
  _globals['_HEALTHREQUEST']._serialized_start=306
  _globals['_HEALTHREQUEST']._serialized_end=402
  _globals['_HEALTHRESPONSE']._serialized_start=404
  _globals['_HEALTHRESPONSE']._serialized_end=513
  _globals['_BARSERVICE']._serialized_start=516
  _globals['_BARSERVICE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
