# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, constr


class Timeframe(Enum):
    field_1m = "1m"
    field_3m = "3m"
    field_5m = "5m"
    field_15m = "15m"
    field_30m = "30m"
    field_1h = "1h"
    field_2h = "2h"
    field_4h = "4h"
    field_1_d = "1D"
    field_1_w = "1W"


class AssetClass(Enum):
    equity = "EQUITY"
    crypto = "CRYPTO"
    etf = "ETF"
    fund = "FUND"


class Asset(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str = Field(..., examples=["BINANCE:BTCUSDT"])
    """
    TradingView identifier, uppercase.
    """
    name: str
    """
    Human-readable asset name.
    """
    exchange: str
    """
    Exchange identifier (typically the prefix before `:` in the symbol).
    """
    type: Optional[str] = Field(None, examples=["crypto", "stock", "etf", "fund"])
    """
    Spec-compatible short type label (e.g. "stock", "crypto"). Mirrors
    assetClass in lower case for backwards compatibility with the
    original REST API spec's /v1/search example payload.

    """
    currency: constr(min_length=3, max_length=3)
    """
    ISO 4217 quote currency.
    """
    asset_class: AssetClass = Field(..., alias="assetClass")
    asset_sub_class: Optional[str] = Field(None, alias="assetSubClass")
    """
    Free-form sub-class (e.g. SPOT, PERP, COMMON).
    """
    isin: Optional[constr(min_length=12, max_length=12)] = None
    """
    ISIN if known; omitted otherwise.
    """
    country: Optional[constr(min_length=2, max_length=2)] = None
    """
    ISO 3166-1 alpha-2 country code.
    """


class Quote(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str = Field(..., examples=["BINANCE:BTCUSDT"])
    timeframe: Timeframe
    price: float
    """
    Close price of the latest closed bar.
    """
    currency: constr(min_length=3, max_length=3)
    """
    Quote currency from the asset catalog.
    """
    ts: int
    """
    Bar open timestamp, epoch seconds UTC.
    """
    stale: bool
    """
    True if the bar is older than `max_age_seconds`.
    """


class Bar(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ts: int
    """
    Bar open timestamp, epoch seconds UTC.
    """
    open: float
    high: float
    low: float
    close: float
    volume: float


class HistoricalResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    symbol: str
    interval: Timeframe
    bars: List[Bar]
    truncated: Optional[bool] = None
    """
    True if the requested range contained more bars than the cap (5000); the most recent are returned.
    """


class SearchResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    results: List[Asset]


class Status(Enum):
    ok = "ok"
    degraded = "degraded"


class HealthResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    status: Status
    grpc_reachable: bool
    """
    True if the gateway can reach BarService over the configured GRPC_TARGET.
    """
    db_reachable: bool
    """
    True if the gateway can SELECT 1 against the configured DATABASE_URL.
    """


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: str
    """
    Machine-readable error code.
    """
    message: str
    """
    Human-readable error message.
    """


class ValidationError(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    loc: List[Union[str, int]]
    msg: str
    type: str


class HTTPValidationError(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    detail: Optional[List[ValidationError]] = None
